# Site settings
title: FAFBv15 Data
email: sseung@princeton.edu
url: https://seung-lab.github.io/fafbv15/
description: "FAFBv15 Data"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: "<br>Seung Lab<br>Princeton Neuroscience Institute<br>Princeton University<br>"

social:
        - title: github
          url: https://github.com/seung-lab/fafbv15

# Build settings
markdown: kramdown
permalink: pretty
